package pt.link.sc.transaction.api.resources.model;

import java.math.BigInteger;
import java.util.Date;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "Represents a card transaction performed by the SCF.")
public abstract class Transaction {

	@ApiModelProperty(value = "The transaction type. " + "\n 1 - Load " + "\n 4 - Invalidation"
			+ "\n 5 - Personalization" + "\n 6 - Debit"
			+ "\n Transaction as provided byt the SCF.", allowEmptyValue = false)
	@NotNull
	private Integer transactionType;

	
	@ApiModelProperty(value = "Version", example = "1.0")
	private String transactionVersion;

	@ApiModelProperty(value = "The  transaction id.", allowEmptyValue = false)
	@NotNull
	private String transactionId;

	@ApiModelProperty(value = "Identifier for transaction group correlation", allowEmptyValue = true)
	private String groupId;

	@ApiModelProperty(value = "transactionDate.", allowEmptyValue = false)
	@NotNull
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
	private Date transactionDate;

	private Integer cardDataModel;

	@ApiModelProperty(value = "The card physical type.")
	private Integer cardPhysicalType;

	private Integer cardIssuer;

	@ApiModelProperty(value = "The card number", allowEmptyValue = false)
	@NotNull
	private BigInteger cardNumb;

	@ApiModelProperty(value = "The card serial number in hexadecimal", allowEmptyValue = false, example = "0433458AD55197")
	@NotNull
	private String cardSerialNumberHexString;

	private Integer cardCalypsoChipRef;

	private Integer cardCalypsoApplType;

	@ApiModelProperty(value = "The card type identifier. DESFIRE corresponds to the value 8", allowEmptyValue = false, example = "8")
	private Integer cardCalypsoApplSubType;

	private Integer cardCalypsoApplIssu;

	
	@ApiModelProperty(value = "MAC from the scf in base 64", allowEmptyValue = false)
	@NotNull
	private String mac;


	private Integer prof1Code;

	private Integer prof1ExpDate;

	private Integer prof2Code;

	private Integer prof2ExpDate;

	private Integer prof3Code;

	private Integer prof3ExpDate;
	
	/*TODO: Are these attributes common in every Transaction Type? They are not in the specification doc.
	 * 
    @ApiModelProperty(value = "The location description")
    private String locationDescription;

	@ApiModelProperty(value = "CSV generated by the scf", allowEmptyValue = false)
	@NotNull
	private String csv;
	
	*/
	
	public Integer getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(Integer transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionVersion() {
		return transactionVersion;
	}

	public void setTransactionVersion(String transactionVersion) {
		this.transactionVersion = transactionVersion;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}


	public Date getTransactionDate() {
		return transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Integer getCardDataModel() {
		return cardDataModel;
	}

	public void setCardDataModel(Integer cardDataModel) {
		this.cardDataModel = cardDataModel;
	}

	public Integer getCardPhysicalType() {
		return cardPhysicalType;
	}

	public void setCardPhysicalType(Integer cardPhysicalType) {
		this.cardPhysicalType = cardPhysicalType;
	}

	public Integer getCardIssuer() {
		return cardIssuer;
	}

	public void setCardIssuer(Integer cardIssuer) {
		this.cardIssuer = cardIssuer;
	}

	public BigInteger getCardNumb() {
		return cardNumb;
	}

	public void setCardNumb(BigInteger cardNumb) {
		this.cardNumb = cardNumb;
	}

	public String getCardSerialNumberHexString() {
		return cardSerialNumberHexString;
	}

	public void setCardSerialNumberHexString(String cardSerialNumberHexString) {
		this.cardSerialNumberHexString = cardSerialNumberHexString;
	}

	public Integer getCardCalypsoChipRef() {
		return cardCalypsoChipRef;
	}

	public void setCardCalypsoChipRef(Integer cardCalypsoChipRef) {
		this.cardCalypsoChipRef = cardCalypsoChipRef;
	}

	public Integer getCardCalypsoApplType() {
		return cardCalypsoApplType;
	}

	public void setCardCalypsoApplType(Integer cardCalypsoApplType) {
		this.cardCalypsoApplType = cardCalypsoApplType;
	}

	public Integer getCardCalypsoApplSubType() {
		return cardCalypsoApplSubType;
	}

	public void setCardCalypsoApplSubType(Integer cardCalypsoApplSubType) {
		this.cardCalypsoApplSubType = cardCalypsoApplSubType;
	}

	public Integer getCardCalypsoApplIssu() {
		return cardCalypsoApplIssu;
	}

	public void setCardCalypsoApplIssu(Integer cardCalypsoApplIssu) {
		this.cardCalypsoApplIssu = cardCalypsoApplIssu;
	}

	public String getMac() {
		return mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public Integer getProf1Code() {
		return prof1Code;
	}

	public void setProf1Code(Integer prof1Code) {
		this.prof1Code = prof1Code;
	}

	public Integer getProf1ExpDate() {
		return prof1ExpDate;
	}

	public void setProf1ExpDate(Integer prof1ExpDate) {
		this.prof1ExpDate = prof1ExpDate;
	}

	public Integer getProf2Code() {
		return prof2Code;
	}

	public void setProf2Code(Integer prof2Code) {
		this.prof2Code = prof2Code;
	}

	public Integer getProf2ExpDate() {
		return prof2ExpDate;
	}

	public void setProf2ExpDate(Integer prof2ExpDate) {
		this.prof2ExpDate = prof2ExpDate;
	}

	public Integer getProf3Code() {
		return prof3Code;
	}

	public void setProf3Code(Integer prof3Code) {
		this.prof3Code = prof3Code;
	}

	public Integer getProf3ExpDate() {
		return prof3ExpDate;
	}

	public void setProf3ExpDate(Integer prof3ExpDate) {
		this.prof3ExpDate = prof3ExpDate;
	}

	@Override
	public String toString() {
		return "Transaction [transactionType=" + transactionType + 
						  ", transactionVersion=" + transactionVersion + 
						  ", transactionId=" + transactionId + 
						  ", groupId=" + groupId + 
						  ", cardDataModel=" + cardDataModel + 
						  ", cardPhysicalType=" + cardPhysicalType + 
						  ", cardIssuer=" + cardIssuer + 
						  ", cardNumb=" + cardNumb + 
						  ", cardSerialNumberHexString=" + cardSerialNumberHexString + 
						  ", cardCalypsoChipRef=" + cardCalypsoChipRef + 
						  ", cardCalypsoApplType=" + cardCalypsoApplType + 
						  ", cardCalypsoApplSubType=" + cardCalypsoApplSubType + 
						  ", cardCalypsoApplIssu=" + cardCalypsoApplIssu + 
						  ", mac=" + mac + 
						  ", prof1Code=" + prof1Code + 
						  ", prof1ExpDate=" + prof1ExpDate + 
						  ", prof2Code=" + prof2Code + 
						  ", prof2ExpDate=" + prof2ExpDate + 
						  ", prof3Code=" + prof3Code + 
						  ", prof3ExpDate=" + prof3ExpDate + "]";				
	}
}