CREATE TABLE [transactions].[CHANNEL_POINTS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EXTERNAL_ID] [varchar](255) NULL,
	[DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[OFFLINE_CARD_OPERATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
	[CORRELATION_ID] [varchar](255) NULL,
	[JSON_CONTENT] [varchar](max) NULL,
	[JSON_CONTENT_CLASS_TYPE_NAME] [varchar](255) NULL,
	[OFFLINE_OPERATION_STATUS] [int] NULL,
	[UUID] [varchar](255) NULL,
	[CREATED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[CHANNEL_POINT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[OFFLINE_TRANSACTION_OPERATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ARGS_JSON] [varchar](255) NULL,
	[CARD_NUMBER] [numeric](19, 0) NULL,
	[MESSAGE] [varchar](255) NULL,
	[MESSAGE_CODE] [varchar](255) NULL,
	[STATUS] [int] NULL,
	[TRANSACTION_ID] [varchar](255) NULL,
	[CREATED_BY_USER_ID] [varchar](255) NULL,
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
	[OFFLINE_CARD_OPERATION_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[INTEGRATION_LOG_TYPES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TYPE_NAME] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[INTEGRATION_LOG_STATES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATE_NAME] [varchar](255) NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[INTEGRATION_LOGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TYPE_ID] [bigint] NOT NULL,
	[STATE_ID] [bigint] NOT NULL,
	[SENDER_ENTITY_ID] [int] NULL,
	[RECEIVER_ENTITY_ID] [int] NULL,
	[SOURCE_MESSAGE_ID] [varchar](40) NULL,
	[INTEGRATION_DATE] [datetime2](7) NULL,
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
	[TRANSFER_DATE] [datetime2](7) NULL,	
	[ERROR_DESC] [varchar](500) NULL,
	[FILE_PATH] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[TRANSACTION_TYPES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACTIVE] [int] NOT NULL,
	[TRANSACTION_TYPE_CODE] [varchar](20) NOT NULL,
	[TRANSACTION_TYPE_NAME] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[TRANSACTION_STATES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACTIVE] [int] NOT NULL,
	[TRANSACTION_STATE_CODE] [varchar](2) NOT NULL,
	[TRANSACTION_STATE_NAME] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[TRANSACTION_STATES_REASONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACTIVE] [int] NOT NULL,
	[TRANSACTION_STATE_ID] [bigint] NOT NULL,
	[TRANSACTION_STATE_REASON_CODE] [varchar](50) NOT NULL,
	[TRANSACTION_STATE_REASON_NAME] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[TRANSACTIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AUTHORIZATION_ID] [bigint],
	[TRANSACTION_STATE_REASON_ID] [bigint],
	[TRANSACTION_STATE_ID] [bigint],
	[TRANSACTION_TYPE_ID] [bigint],
	[INTEGRATION_LOG_ID] [bigint],
	[GROUP_ID] [varchar](255),
	[TRANSACTION_DATE] [datetime2](7),
	[LOAD_OPER] [int],
	[TICKET_RELOAD_DATE] [datetime2](7),
	[TICKET_RELOAD_MACHINE_CODE] [int],
	[TICKET_RELOAD_NUMBER_DAILY] [int],
	[CORR_TRANSACTION_IDENTIFIER] [varchar](255),
	[CORR_TICK_RELOAD_MACHINE_CODE] [int],
	[CORR_TICK_RELOAD_NUMBER_DAILY] [int],
	[CORR_CARD_DATA_MODEL_ID] [int],
	[VINH_SERI_NR] [numeric](19, 0),
	[QUANTITY] [int],
	[POS_ID] [varchar](255),
	[FISCAL_NUMBER] [numeric](19, 0),
	[INVOICE_NUMBER] [varchar](255),
	[CARD_DATA_MODEL_ID] [int],
	[CARD_PHYSICAL_TYPE_ID] [int],
	[NETWORK_CODE] [int],
	[CARD_NUMBER] [numeric](19, 0),
	[CARD_SERIAL_NUMBER] [numeric](19, 0),
	[ENTITY_ID] [int],
	[CORR_CARD_NUMBER] [int],
	[CORR_CARD_SERIAL_NUMBER] [numeric](19, 0),
	[TICKET_OPERATOR_CODE] [int],
	[TICKET_CODE] [int],
	[CHANNEL_POINT_ID] [bigint],
	[CONTRACT_BINARY] [varchar](255),
	[CONTRACT_POSITION] [int],
	[PREVIOUS_CONTRACT_BINARY] [varchar](255),
	[FIRST_DATE_TIME_ENTRANCE] [datetime2](7),
	[CORR_TICK_OPER_CODE] [int],
	[CORR_TICK_CODE] [int],
	[PRICE] [int],
	[CORR_PRICE] [int],
	[PAYMENT_MEAN] [int],
	[COMISSION] [int],
	[PIN_BLOCK] [varchar](30),
	[UUID] [varchar](255),
	[CREATED_BY_USER_ID] [int],
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
	[OFFLINE_CARD_OPERATION_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[TRANSACTION_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRANSACTION_ID] [bigint] NOT NULL,
	[PROFILE_CODE] [int],
	[PROF_COMPANY_OPER] [int],
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[VALIDATION_TYPES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[VALIDATION_TYPE_NAME] [varchar](35) NOT NULL,
	[VALIDATION_TYPE_CODE] [varchar](15),
	[ACTIVE] [int]
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[VALIDATION_STATES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[VALIDATION_STATE_CODE] [varchar](3) NOT NULL,
	[VALIDATION_STATE_NAME] [varchar](30) NOT NULL,
	[ACTIVE] [int] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[VALIDATION_STATES_REASONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[VALIDATION_STATE_ID] [bigint] NOT NULL,
	[VALIDATION_STATE_REASON_CODE] [varchar](50) NOT NULL,
	[VALIDATION_STATE_REASON_NAME] [varchar](80) NOT NULL,	
	[ACTIVE] [int] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[VALIDATIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INTEGRATION_LOG_ID] [bigint],
	[VALIDATION_TYPE_ID] [bigint],
	[VALIDATION_STATE_ID] [bigint],
	[VALIDATION_STATE_REASON_ID] [bigint],
	[VALIDATION_IDENTIFIER] [varchar](100),
	[VALIDATION_DATE] [datetime2](7),
	[GROUP_ID] [varchar](255),
	[OBSOLETE_FIRST_ENTRY_OPER] [int],
	[PREV_EVENT_OPER] [int],
	[PREV_EVENT_BINARY] [varchar](100),
	[EVENT_BINARY] [varchar](255),
	[EVENT_SUCCESS_CODE] [int],
	[VALIDATOR_MACHINE_CODE] [int],
	[CARD_DATA_MODEL_ID] [int],
	[CARD_PHYSICAL_TYPE_ID] [int],
	[CARD_NUMBER] [numeric](19, 0),
	[CARD_SERIAL_NUMBER] [numeric](19, 0),
	[MAC] [varchar](100),
	[CONT_LOCATION] [int],
	[FIRST_DATA_TIME_ENTRANCE] [datetime2](7),
	[STOP] [int],
	[RUN_CODE] [int],
	[DIRECTION] [int],
	[ROUTE] [int],
	[PREV_HIST_RFU] [int],
	[HIST_RFU] [int],
	[RFU] [int],
	[ORIGIN] [varchar](100),
	[DESTINATION] [int],
	[ENTITY_ID] [int],
	[CONTRACT_POSITION] [int],
	[TICKET_CODE] [int],
	[TICKET_OPERATOR_CODE] [int],
	[TICKET_RELOAD_MACHINE_CODE] [int],
	[TICKET_RELOAD_DATE] [datetime2](7),
	[TICKET_RELOAD_NUMBER_DAILY] [int],
	[COUNTER_READ_BINARY] [varchar](50),
	[COUNTER_WRITTEN_BINARY] [varchar](50),
	[CREATED_BY_USER_ID] [int],	
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
	[UUID] [varchar](255)
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[VALIDATION_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[VALIDATION_ID] [bigint] NOT NULL,
	[PROFILE_CODE] [int],
	[PROF_COMPANY_OPER] [int],
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[AUTHORIZATION_TYPES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AUTHORIZATION_TYPE_NAME] [varchar](30) NOT NULL,
	[ACTIVE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[AUTHORIZATIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CARD_ID] [bigint],
	[AUTHORIZATION_TYPE_ID] [bigint],
	[UUID] [varchar](255),
	[AMOUNT] [bigint],
	[CURRENCY_CODE] [varchar](255),
	[AUTHORIZATION_STATE] [int],
	[PERFORMED_ON] [datetime2](7),
	[CARD_EXPIRATION_DATE] [datetime2](7),
	[AUTHORIZATION_EXPIRATION_DATE] [datetime2](7),
	[REASON] [varchar](255),
	[CHANNEL_POINT_ID] [bigint],
	[CREATED_BY_USER_ID] [int],
	[CREATED_ON_DATE] [datetime2](7),
	[LAST_MODIFIED_BY_USER_ID] [int],
	[LAST_MODIFIED_ON_DATE] [datetime2](7),
	[VERSION] [int] NOT NULL,	
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [transactions].[CARDS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CARD_NUMBER] [numeric](19, 0),
	[CARD_ISSUER] [int],
	[CURRENCY_CODE] [varchar](255),
	[CARD_SERIAL_NUMBER] [numeric](19, 0),
	[CARD_STATUS] [int],
	[ACTIVATION_DATE] [datetime2](7),
	[EXPIRATION_DATE] [datetime2](7),
	[CARD_TYPE] [int],
	[CREATED_BY_USER_ID] [int],	
	[CREATED_ON_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY_USER_ID] [varchar](255) NULL,
	[LAST_MODIFIED_ON_DATE] [datetime2](7) NULL,
	[VERSION] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [transactions].[INTEGRATION_LOGS]  WITH CHECK ADD  CONSTRAINT [INTEGRATIONS_LOGS_TYPES_ID] FOREIGN KEY([TYPE_ID])
REFERENCES [transactions].[INTEGRATION_LOG_TYPES] ([ID])
GO
ALTER TABLE [transactions].[INTEGRATION_LOGS] CHECK CONSTRAINT [INTEGRATIONS_LOGS_TYPES_ID]

GO
ALTER TABLE [transactions].[INTEGRATION_LOGS]  WITH CHECK ADD  CONSTRAINT [INTEGRATIONS_LOGS_STATES_ID] FOREIGN KEY([STATE_ID])
REFERENCES [transactions].[INTEGRATION_LOG_STATES] ([ID])
GO
ALTER TABLE [transactions].[INTEGRATION_LOGS] CHECK CONSTRAINT [INTEGRATIONS_LOGS_STATES_ID]

GO
ALTER TABLE [transactions].[AUTHORIZATIONS]  WITH CHECK ADD  CONSTRAINT [AUTHORIZATIONS_CHANNEL_POINTS_ID] FOREIGN KEY([CHANNEL_POINT_ID])
REFERENCES [transactions].[CHANNEL_POINTS] ([ID])
GO
ALTER TABLE [transactions].[AUTHORIZATIONS] CHECK CONSTRAINT [AUTHORIZATIONS_CHANNEL_POINTS_ID]

GO
ALTER TABLE [transactions].[AUTHORIZATIONS]  WITH CHECK ADD  CONSTRAINT [AUTHORIZATIONS_CARDS_ID] FOREIGN KEY([CARD_ID])
REFERENCES [transactions].[CARDS] ([ID])
GO
ALTER TABLE [transactions].[AUTHORIZATIONS] CHECK CONSTRAINT [AUTHORIZATIONS_CARDS_ID]

GO
ALTER TABLE [transactions].[AUTHORIZATIONS]  WITH CHECK ADD  CONSTRAINT [AUTHORIZATIONS_TYPES_ID] FOREIGN KEY([AUTHORIZATION_TYPE_ID])
REFERENCES [transactions].[AUTHORIZATION_TYPES] ([ID])
GO
ALTER TABLE [transactions].[AUTHORIZATIONS] CHECK CONSTRAINT [AUTHORIZATIONS_TYPES_ID]

GO
ALTER TABLE [transactions].[VALIDATION_PROFILES]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_PROFILES_ID] FOREIGN KEY([VALIDATION_ID])
REFERENCES [transactions].[VALIDATIONS] ([ID])
GO
ALTER TABLE [transactions].[VALIDATION_PROFILES] CHECK CONSTRAINT [VALIDATIONS_PROFILES_ID]

GO
ALTER TABLE [transactions].[VALIDATIONS]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_INTEGRATION_LOGS_ID] FOREIGN KEY([INTEGRATION_LOG_ID])
REFERENCES [transactions].[INTEGRATION_LOGS] ([ID])
GO
ALTER TABLE [transactions].[VALIDATIONS] CHECK CONSTRAINT [VALIDATIONS_INTEGRATION_LOGS_ID]

GO
ALTER TABLE [transactions].[VALIDATIONS]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_TYPES_ID] FOREIGN KEY([VALIDATION_TYPE_ID])
REFERENCES [transactions].[VALIDATION_TYPES] ([ID])
GO
ALTER TABLE [transactions].[VALIDATIONS] CHECK CONSTRAINT [VALIDATIONS_TYPES_ID]

GO
ALTER TABLE [transactions].[VALIDATIONS]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_STATES_ID] FOREIGN KEY([VALIDATION_STATE_ID])
REFERENCES [transactions].[VALIDATION_STATES] ([ID])
GO
ALTER TABLE [transactions].[VALIDATIONS] CHECK CONSTRAINT [VALIDATIONS_STATES_ID]

GO
ALTER TABLE [transactions].[VALIDATIONS]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_STATES_REASONS_ID] FOREIGN KEY([VALIDATION_STATE_REASON_ID])
REFERENCES [transactions].[VALIDATION_STATES_REASONS] ([ID])
GO
ALTER TABLE [transactions].[VALIDATIONS] CHECK CONSTRAINT [VALIDATIONS_STATES_REASONS_ID]

GO
ALTER TABLE [transactions].[VALIDATION_STATES_REASONS]  WITH CHECK ADD  CONSTRAINT [VALIDATIONS_STATES_REASONS_STATES_ID] FOREIGN KEY([VALIDATION_STATE_ID])
REFERENCES [transactions].[VALIDATION_STATES] ([ID])
GO
ALTER TABLE [transactions].[VALIDATION_STATES_REASONS] CHECK CONSTRAINT [VALIDATIONS_STATES_REASONS_STATES_ID]

GO
ALTER TABLE [transactions].[TRANSACTION_PROFILES]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_PROFILES_ID] FOREIGN KEY([TRANSACTION_ID])
REFERENCES [transactions].[TRANSACTIONS] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTION_PROFILES] CHECK CONSTRAINT [TRANSACTIONS_PROFILES_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_AUTHORIZATIONS_ID] FOREIGN KEY([AUTHORIZATION_ID])
REFERENCES [transactions].[AUTHORIZATIONS] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTIONS_AUTHORIZATIONS_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTION_STATES_REASONS_ID] FOREIGN KEY([TRANSACTION_STATE_REASON_ID])
REFERENCES [transactions].[TRANSACTION_STATES_REASONS] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTION_STATES_REASONS_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_STATES_ID] FOREIGN KEY([TRANSACTION_STATE_ID])
REFERENCES [transactions].[TRANSACTION_STATES] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTIONS_STATES_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_TYPES_ID] FOREIGN KEY([TRANSACTION_TYPE_ID])
REFERENCES [transactions].[TRANSACTION_TYPES] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTIONS_TYPES_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_INTEGRATION_LOGS_ID] FOREIGN KEY([INTEGRATION_LOG_ID])
REFERENCES [transactions].[INTEGRATION_LOGS] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTIONS_INTEGRATION_LOGS_ID]

GO
ALTER TABLE [transactions].[TRANSACTION_STATES_REASONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_STATES_REASONS_STATES_ID] FOREIGN KEY([TRANSACTION_STATE_ID])
REFERENCES [transactions].[TRANSACTION_STATES] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTION_STATES_REASONS] CHECK CONSTRAINT [TRANSACTIONS_STATES_REASONS_STATES_ID]

GO
ALTER TABLE [transactions].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONS_CHANNEL_POINTS_ID] FOREIGN KEY([CHANNEL_POINT_ID])
REFERENCES [transactions].[CHANNEL_POINTS] ([ID])
GO
ALTER TABLE [transactions].[TRANSACTIONS] CHECK CONSTRAINT [TRANSACTIONS_CHANNEL_POINTS_ID]

GO
ALTER TABLE [transactions].[OFFLINE_CARD_OPERATION]  WITH CHECK ADD  CONSTRAINT [OFFLINE_CARD_OPERATION_CHANNEL_POINTS_ID] FOREIGN KEY([CHANNEL_POINT_ID])
REFERENCES [transactions].[CHANNEL_POINTS] ([ID])
GO
ALTER TABLE [transactions].[OFFLINE_CARD_OPERATION] CHECK CONSTRAINT [OFFLINE_CARD_OPERATION_CHANNEL_POINTS_ID]

GO
ALTER TABLE [transactions].[OFFLINE_TRANSACTION_OPERATION]  WITH CHECK ADD  CONSTRAINT [OFFLINE_TRANSACTION_CARD_OPERATION_ID] FOREIGN KEY([OFFLINE_CARD_OPERATION_ID])
REFERENCES [transactions].[OFFLINE_CARD_OPERATION] ([ID])
GO
ALTER TABLE [transactions].[OFFLINE_TRANSACTION_OPERATION] CHECK CONSTRAINT [OFFLINE_TRANSACTION_CARD_OPERATION_ID]